/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "ac-primary": "var(--ac-primary)",
        "ac-primary-light": "var(--ac-primary-light)",
        "ac-primary-dark": "var(--ac-primary-dark)",
        "ac-cream": "var(--ac-cream)",
        "ac-cream-dark": "var(--ac-cream-dark)",
        "ac-sand": "var(--ac-sand)",
        "ac-wood": "var(--ac-wood)",
        "ac-wood-dark": "var(--ac-wood-dark)",
        "ac-text": "var(--ac-text)",
        "ac-green": "var(--ac-green)",
        "ac-green-light": "var(--ac-green-light)",
        "ac-pink": "var(--ac-pink)",
        "ac-yellow": "var(--ac-yellow)",
        "ac-orange": "var(--ac-orange)",
        "ac-brown": "var(--ac-brown)",
      },
      borderRadius: {
        "ac-sm": "var(--ac-radius-sm)",
        "ac-md": "var(--ac-radius-md)",
        "ac-lg": "var(--ac-radius-lg)",
        "ac-xl": "var(--ac-radius-xl)",
      },
      boxShadow: {
        ac: "var(--ac-shadow)",
        "ac-hover": "var(--ac-shadow-hover)",
        "ac-inset": "var(--ac-shadow-inset)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
  daisyui: {
    themes: [
      {
        nord: {
          primary: "#2abaaa",
          "primary-content": "#ffffff",
          secondary: "#8bc34a",
          "secondary-content": "#ffffff",
          accent: "#f48fb1",
          "accent-content": "#877358",
          neutral: "#8d6e63",
          "neutral-content": "#ffffff",
          "base-100": "#f7f3e7",
          "base-200": "#ece6d4",
          "base-300": "#ddd6c0",
          "base-content": "#877358",
          info: "#2abaaa",
          success: "#8bc34a",
          warning: "#ffb74d",
          error: "#ef5350",
        },
      },
      {
        night: {
          primary: "#2abaaa",
          "primary-content": "#ffffff",
          secondary: "#8bc34a",
          "secondary-content": "#ffffff",
          accent: "#f48fb1",
          "accent-content": "#e2d6c8",
          neutral: "#8d6e63",
          "neutral-content": "#ffffff",
          "base-100": "#374063",
          "base-200": "#2d3554",
          "base-300": "#232a47",
          "base-content": "#e2d6c8",
          info: "#2abaaa",
          success: "#8bc34a",
          warning: "#ffb74d",
          error: "#ef5350",
        },
      },
    ],
    darkTheme: "night",
    logs: false,
  },
};
